/*
 * LED.c
 *
 *  Created on: May 12, 2015
 *      Author: XuanHung
 */

#include "LED.h"

void LED_InitController(){
	Chip_GPIO_SetPinDIROutput(LPC_GPIO,USER_LED_PORT,USER_LED_PIN);

	Chip_GPIO_SetPinDIROutput(LPC_GPIO,DIRSW_LED_PORT,UP_SW_LED_PIN);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO,DIRSW_LED_PORT,DW_SW_LED_PIN);

	Chip_GPIO_SetPinDIROutput(LPC_GPIO,SEN_LED_PORT,SEN1_LED_PIN);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO,SEN_LED_PORT,SEN2_LED_PIN);

	Chip_GPIO_SetPinDIROutput(LPC_GPIO,LM_LED_PORT,UP_LM_LED_PIN);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO,LM_LED_PORT,DW_LM_LED_PIN);
}

void LED_TurnOnUserLED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,USER_LED_PORT,USER_LED_PIN);
}
void LED_TurnOffUserLED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,USER_LED_PORT,USER_LED_PIN);
}
void LED_TurnOnUPSWLED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,DIRSW_LED_PORT,UP_SW_LED_PIN);
	//Chip_GPIO_SetPinOutLow(LPC_GPIO,DIRSW_LED_PORT,DW_SW_LED_PIN);
}
void LED_TurnOffUPSWLED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,DIRSW_LED_PORT,UP_SW_LED_PIN);
}
void LED_TurnOnDWSWLED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,DIRSW_LED_PORT,DW_SW_LED_PIN);
	//Chip_GPIO_SetPinOutLow(LPC_GPIO,DIRSW_LED_PORT,UP_SW_LED_PIN);
}
void LED_TurnOffDWSWLED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,DIRSW_LED_PORT,DW_SW_LED_PIN);
}

void LED_TurnOnSen1LED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,SEN_LED_PORT,SEN1_LED_PIN);
}
void LED_TurnOffSen1LED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,SEN_LED_PORT,SEN1_LED_PIN);
}
void LED_TurnOnSen2LED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,SEN_LED_PORT,SEN2_LED_PIN);
}
void LED_TurnOffSen2LED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,SEN_LED_PORT,SEN2_LED_PIN);
}

void LED_TurnOnUPLMLED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,LM_LED_PORT,UP_LM_LED_PIN);
	//Chip_GPIO_SetPinOutLow(LPC_GPIO,DIRSW_LED_PORT,DW_LM_LED_PIN);
}
void LED_TurnOffUPLMLED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,LM_LED_PORT,UP_LM_LED_PIN);
}

void LED_TurnOnDWLMLED(){
	Chip_GPIO_SetPinOutHigh(LPC_GPIO,LM_LED_PORT,DW_LM_LED_PIN);
	//Chip_GPIO_SetPinOutLow(LPC_GPIO,DIRSW_LED_PORT,UP_LM_LED_PIN);
}
void LED_TurnOffDWLMLED(){
	Chip_GPIO_SetPinOutLow(LPC_GPIO,LM_LED_PORT,DW_LM_LED_PIN);
}
